import { dirname, join, relative, resolve } from "@std/path";
import {
  bool,
  type Command,
  defineCommand,
  str,
} from "../command.ts";
import type { ResourceKind } from "../clients/types.ts";
import { CliError } from "../errors.ts";
import { emit } from "../envelope.ts";
import { linkFilePath, readOwnLinkFile } from "../config.ts";
import { parseKind } from "../resolve/link.ts";
import { kindDisplay } from "../build/detect-kind.ts";
import { resolveEnvironmentName } from "../resolve/environment.ts";
import { envFileOf, mergeEnvBuild } from "../build/config.ts";
import { VERSION } from "../version.ts";

const SECRET_NAME = "PBC_TOKEN";
const LEGACY_SECRET_NAME = "PB_TOKEN";

const ACTION_KINDS: Record<ResourceKind, string> = {
  pocketbases: "pb",
  frontends: "frontend",
  backends: "backend",
};

export const CI_INIT_USAGE =
  "Usage: pbc ci init [pb|frontend|backend] [--out <path>] [--branch <name>] [--force] [--env <name>]";

export type GitRunner = (
  args: string[],
  cwd: string,
) => Promise<{ code: number; stdout: string }>;

export const runGit: GitRunner = async (args, cwd) => {
  const child = new Deno.Command("git", {
    args,
    cwd,
    stdout: "piped",
    stderr: "null",
  }).spawn();
  const { code, stdout } = await child.output();
  return { code, stdout: new TextDecoder().decode(stdout).trim() };
};

async function gitRoot(cwd: string, git: GitRunner): Promise<string | null> {
  const r = await git(["rev-parse", "--show-toplevel"], cwd);
  return r.code === 0 && r.stdout ? r.stdout : null;
}

async function currentBranch(
  cwd: string,
  git: GitRunner,
): Promise<string | null> {
  const r = await git(["symbolic-ref", "--short", "HEAD"], cwd);
  return r.code === 0 && r.stdout ? r.stdout : null;
}

async function defaultBranch(
  cwd: string,
  git: GitRunner,
): Promise<string | null> {
  const r = await git(
    ["symbolic-ref", "--short", "refs/remotes/origin/HEAD"],
    cwd,
  );
  if (r.code !== 0 || !r.stdout) return null;
  return r.stdout.replace(/^origin\//, "") || null;
}

export function workflowSlug(workingDirectory: string): string | undefined {
  if (workingDirectory === "." || workingDirectory === "") return undefined;
  const slug = workingDirectory.split("/").filter((p) => p && p !== ".").join(
    "-",
  );
  return slug || undefined;
}

async function isTracked(
  root: string,
  git: GitRunner,
  path: string,
): Promise<boolean> {
  const r = await git(["ls-files", "--error-unmatch", "--", path], root);
  return r.code === 0;
}

function toPosix(path: string): string {
  return path.split("\\").join("/");
}

const YAML_PLAIN = /^[A-Za-z0-9_][A-Za-z0-9 ._/@+-]*$/;
export function yamlScalar(value: string): string {
  return YAML_PLAIN.test(value) && !value.endsWith(" ")
    ? value
    : JSON.stringify(value);
}

export type WorkflowOptions = {
  kind: ResourceKind;
  workingDirectory: string;
  branch: string;
  environment?: string;
  version: string;
  workflowPath: string;
};

export function renderWorkflow(opts: WorkflowOptions): string {
  const { kind, workingDirectory, branch, environment, version, workflowPath } =
    opts;
  const root = workingDirectory === ".";
  const slug = workflowSlug(workingDirectory);
  const jobName = slug ? `Deploy ${slug}` : "Deploy";
  const group = slug
    ? `deploy-${slug}-${environment ?? "production"}`
    : `deploy-${environment ?? "production"}`;
  const pathsLine = slug
    ? `\n    paths: [${yamlScalar(`${workingDirectory}/**`)}, ${
      yamlScalar(workflowPath)
    }]`
    : "";

  const withLines = [
    `          token: \${{ secrets.${SECRET_NAME} }}`,
    `          kind: ${ACTION_KINDS[kind]}`,
  ];
  if (!root) {
    withLines.push(
      `          working-directory: ${yamlScalar(workingDirectory)}`,
    );
  }
  if (environment) {
    withLines.push(`          env: ${yamlScalar(environment)}`);
  }

  return `# Generated by \`pbc ci init\`. Edit freely — re-running the
# command leaves this file alone unless you pass --force.
# See https://pocketbasecloud.com/docs/ci-cd/reference
name: ${yamlScalar(jobName)}

on:
  push:
    branches: [${yamlScalar(branch)}]${pathsLine}
  workflow_dispatch:

concurrency:
  group: ${yamlScalar(group)}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: pocketbasecloud/cli/action@v${version}
        with:
${withLines.join("\n")}
`;
}

async function namesLegacySecret(path: string): Promise<boolean> {
  try {
    return (await Deno.readTextFile(path)).includes(
      `secrets.${LEGACY_SECRET_NAME}`,
    );
  } catch {
    return false;
  }
}

export function makeCiCommands(
  deps: {
    cwd: () => string;
    git?: GitRunner;
  },
): Record<string, Command> {
  const git = deps.git ?? runGit;

  return {
    "ci init": defineCommand({
      path: ["ci", "init"],
      usage:
        "pbc ci init [pb|frontend|backend] [--out <path>] [--branch <name>] [--force] [--env <name>]",
      summary: "Write a GitHub Actions workflow that deploys this directory.",
      details: `Writes .github/workflows/deploy.yml (or deploy-<path>.yml, when this
directory is not the repo root — nested folders become deploy-apps-web.yml),
using the official pocketbasecloud/cli/action. Nothing in the cloud is
touched, and no login is needed — like \`pbc init\`, it only inspects the
directory and the surrounding git repo.

The kind comes from the argument, or from pbc.json's existing binding. The
branch defaults to the one currently checked out; --branch overrides it.
--out picks a different file path. An existing file is left alone unless
--force is passed.

Prints the two remaining one-time steps: copying an access token from the
portal's Account page, and adding it as a repository secret named PBC_TOKEN.`,
      args: [{
        name: "kind",
        required: false,
        description: "pb, frontend, or backend; defaults to the bound resource",
      }],
      flags: {
        out: str({
          description: "Workflow file path. Defaults under .github/workflows/.",
        }),
        branch: str({
          description:
            "Branch to deploy on push. Defaults to the branch currently checked out.",
        }),
        force: bool({ description: "Overwrite an existing workflow file." }),
        env: str({
          description:
            "pbc.json environment to pin in the workflow. Only --env is written; " +
            "PBC_ENV is ignored, because the answer is committed.",
        }),
      },
      run: async (input, ctx) => {
        const cwd = deps.cwd();
        const own = await readOwnLinkFile(cwd);
        if (!own.projectId) {
          throw new CliError(
            `No pbc.json here. Deploy once from your computer first — ` +
              `\`pbc pocketbase deploy\`, \`pbc frontend deploy\`, or ` +
              `\`pbc backend deploy\` — then run \`pbc ci init\` again.`,
              { code: "USAGE" });
        }

        const token = ctx.args[0];
        let kind: ResourceKind | undefined;
        if (token) {
          const parsed = parseKind(token);
          if (!parsed) {
            throw new CliError(
              `Unknown kind "${token}". ${CI_INIT_USAGE}`,
              { code: "USAGE" },
            );
          }
          kind = parsed;
        } else {
          kind = own.kind;
        }
        if (!kind) {
          throw new CliError(
            `This directory is not bound to a resource, so there is no kind to ` +
              `write a workflow for. ${CI_INIT_USAGE}`, { code: "USAGE" });
        }

        const root = await gitRoot(cwd, git);
        if (!root) {
          throw new CliError(
            `Not a git repository. \`pbc ci init\` writes ` +
              `.github/workflows/, which only makes sense inside one.`,
              { code: "USAGE" });
        }

        const relDir = relative(root, cwd);
        const workingDirectory = relDir === "" ? "." : toPosix(relDir);
        const slug = workflowSlug(workingDirectory);
        const defaultOut = join(
          root,
          ".github",
          "workflows",
          slug ? `deploy-${slug}.yml` : "deploy.yml",
        );
        const outPath = input.out ? resolve(cwd, input.out) : defaultOut;
        const workflowPath = toPosix(relative(root, outPath));

        let branch = input.branch;
        let onDetachedHead = false;
        if (!branch) {
          branch = (await currentBranch(root, git)) ?? undefined;
        }
        if (!branch) {
          onDetachedHead = true;
          branch = (await defaultBranch(root, git)) ?? undefined;
        }
        if (!branch) {
          branch = "main";
        }

        const choice = resolveEnvironmentName(own, { flag: input.env, env: {} });
        const environment = choice.explicit ? choice.name : undefined;

        const version = VERSION;
        const workflow = renderWorkflow({
          kind,
          workingDirectory,
          branch,
          environment,
          version,
          workflowPath,
        });

        const warnings: string[] = [];
        const pbJsonPath = await linkFilePath(cwd);
        const pbJsonRel = toPosix(relative(root, pbJsonPath));
        if (!(await isTracked(root, git, pbJsonPath))) {
          warnings.push(
            `${pbJsonRel} is not tracked by git — GitHub will not see it. Either ` +
              `\`git add ${pbJsonRel}\` and commit it, or pass --project ` +
              `<name|id> on every deploy.`,
          );
        }
        const build = mergeEnvBuild(own, choice.name);
        const envFile = envFileOf(build);
        if (envFile) {
          const envFilePath = join(cwd, envFile);
          if (!(await isTracked(root, git, envFilePath))) {
            warnings.push(
              `The env file this environment pushes ("${envFile}") is ` +
                `not in git, so CI will not find it and the deploy will fail ` +
                `with "Env file not found". Use \`pbc env set\` instead — ` +
                `see the CI/CD guide, Step 6.`,
            );
          }
        }
        if (!input.branch && onDetachedHead) {
          warnings.push(
            `HEAD is not a branch, so the workflow deploys on pushes to ` +
              `"${branch}". Pass --branch <name> to pin a different one.`,
          );
        }
        if (kind === "pocketbases") {
          warnings.push(
            `The action masks this deploy's admin credentials automatically, ` +
              `but only for output it produces itself — any step you add that ` +
              `prints the deploy JSON yourself will not be masked.`,
          );
        }

        let exists = false;
        try {
          await Deno.stat(outPath);
          exists = true;
        } catch {
          // absent — nothing to guard
        }
        if (exists && input.force !== true) {
          emit(
            ctx.flags.json,
            { path: outPath, written: false },
            `${outPath} already exists.\nPass --force to overwrite it.`,
          );
          return 0;
        }

        if (exists && await namesLegacySecret(outPath)) {
          warnings.push(
            `the workflow being replaced read \`secrets.${LEGACY_SECRET_NAME}\`; ` +
              `the new one reads \`secrets.${SECRET_NAME}\`. Add that secret, or ` +
              `edit the \`token:\` line back to the one you already have.`,
          );
        }

        await Deno.mkdir(dirname(outPath), { recursive: true });
        await Deno.writeTextFile(outPath, workflow);

        emit(
          ctx.flags.json,
          {
            path: outPath,
            kind,
            workingDirectory,
            branch,
            environment: choice.name,
            secretName: SECRET_NAME,
            warnings,
            written: true,
          },
          () =>
            [
              `Wrote ${outPath} — deploys this ${
                kindDisplay(kind)
              } on every push to ${branch}.`,
              ...warnings.map((w) => `Warning: ${w}`),
              ``,
              `Two things left, both one-time:`,
              `  1. Copy your token: portal → Account → CLI access token → Copy.`,
              `  2. Add it as a repository secret named ${SECRET_NAME}:`,
              `     Settings → Secrets and variables → Actions → New repository secret.`,
              ``,
              `Then commit both files, from ${root}:`,
              `  git add ${workflowPath} ${pbJsonRel}`,
              `  git commit -m "Deploy on push"`,
            ].join("\n"),
        );
        return 0;
      },
    }),
  };
}
