import type { CommandRegistry } from "../src/command.ts";
import { canonicalKeys, kebabCase } from "../src/command.ts";
import type { CommandSpec, FlagSpec } from "../src/usage.ts";

export function commandSpecs(
  registry: CommandRegistry,
): Record<string, CommandSpec> {
  const out: Record<string, CommandSpec> = {};
  for (const key of canonicalKeys(registry)) {
    const command = registry[key];
    out[key] = {
      usage: command.usage,
      summary: command.summary,
      ...(command.details !== undefined ? { details: command.details } : {}),
      ...(command.needs && command.needs.length > 0
        ? { needs: command.needs as CommandSpec["needs"] }
        : {}),
      args: command.args,
      flags: Object.entries(command.flags).map(([prop, f]) => ({
        name: kebabCase(prop),
        type: f.type,
        required: f.required === true,
        ...(f.choices ? { choices: f.choices } : {}),
        description: f.description,
        ...(f.renamedTo ? { renamedTo: kebabCase(f.renamedTo) } : {}),
        ...(f.retired ? { retired: f.retired } : {}),
      })) as FlagSpec[],
    };
  }
  return out;
}

if (import.meta.main) {
  const registry: CommandRegistry = {};
  const { registerCommands } = await import("../src/commands/index.ts");
  registerCommands(registry);
  const body = JSON.stringify(commandSpecs(registry), null, 2);
  const header = `// Generated by \`deno task manifest\` (scripts/gen-manifest.ts) from the\n// command registry, and re-run by \`deno task build\`. Do not edit by hand — the docs site imports COMMANDS\n// from this file and it must stay pure data.\n\nexport type ArgSpec = { name: string; required: boolean; description?: string };\nexport type FlagSpec = { name: string; type: "string" | "boolean" | "path"; required: boolean; choices?: string[]; description?: string; /** Accepted as an alias for this flag; do not document it as its own. */ renamedTo?: string; /** Parsed and discarded; do not document it as usable. */ retired?: { since: string; note: string } };\nexport type Need = \`target:\${string}\` | { explicit: true };\nexport type CommandSpec = { usage: string; summary: string; details?: string; /** Target resolution the command needs: which resource kind, and whether a lone candidate may be auto-selected. */ needs?: Need[]; args: ArgSpec[]; flags: FlagSpec[] };\n`;
  await Deno.writeTextFile(
    new URL("../src/usage.ts", import.meta.url),
    header + `export const COMMANDS: Record<string, CommandSpec> = ${body};\n`,
  );
}
