// Generated by `deno task manifest` (scripts/gen-manifest.ts) from the
// command registry, and re-run by `deno task build`. Do not edit by hand — the docs site imports COMMANDS
// from this file and it must stay pure data.

export type ArgSpec = { name: string; required: boolean; description?: string };
export type FlagSpec = { name: string; type: "string" | "boolean" | "path"; required: boolean; choices?: string[]; description?: string; /** Accepted as an alias for this flag; do not document it as its own. */ renamedTo?: string; /** Parsed and discarded; do not document it as usable. */ retired?: { since: string; note: string } };
export type Need = `target:${string}` | { explicit: true };
export type CommandSpec = { usage: string; summary: string; details?: string; /** Target resolution the command needs: which resource kind, and whether a lone candidate may be auto-selected. */ needs?: Need[]; args: ArgSpec[]; flags: FlagSpec[] };
export const COMMANDS: Record<string, CommandSpec> = {
  "login": {
    "usage": "pbc login [--token <t>]",
    "summary": "Log in to PocketBase Cloud via browser, or with an access token.",
    "args": [],
    "flags": [
      {
        "name": "token",
        "type": "string",
        "required": false,
        "description": "CLI access token from the portal's Account page (skips the browser flow)"
      }
    ]
  },
  "logout": {
    "usage": "pbc logout",
    "summary": "Log out of PocketBase Cloud.",
    "args": [],
    "flags": []
  },
  "whoami": {
    "usage": "pbc whoami",
    "summary": "Show the logged-in PocketBase Cloud account.",
    "args": [],
    "flags": []
  },
  "pocketbase ls": {
    "usage": "pbc pocketbase ls",
    "summary": "List PocketBase instances in a project.",
    "args": [],
    "flags": []
  },
  "pocketbase info": {
    "usage": "pbc pocketbase info (<name>|--name <name>|--id <id>) [--env <name>]",
    "summary": "Show PocketBase instance details.",
    "needs": [
      "target:pocketbases"
    ],
    "args": [
      {
        "name": "name",
        "required": false,
        "description": "Positional name, alternative to --name/--id"
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Which PocketBase to show. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The instance's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "pocketbase rm": {
    "usage": "pbc pocketbase rm (<name>|--name <name>|--id <id>) [--yes] [--env <name>]",
    "summary": "Delete a PocketBase instance.",
    "needs": [
      "target:pocketbases",
      {
        "explicit": true
      }
    ],
    "args": [
      {
        "name": "name",
        "required": false,
        "description": "Positional name, alternative to --name/--id"
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Which PocketBase to delete. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The instance's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "pocketbase domain add": {
    "usage": "pbc pocketbase domain add <domain> --name <name> [--env <name>]",
    "summary": "Add a custom domain.",
    "needs": [
      "target:pocketbases",
      {
        "explicit": true
      }
    ],
    "args": [
      {
        "name": "domain",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Which PocketBase. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The instance's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "pocketbase domain verify": {
    "usage": "pbc pocketbase domain verify <domain> --name <name> [--env <name>]",
    "summary": "Verify a custom domain.",
    "needs": [
      "target:pocketbases",
      {
        "explicit": true
      }
    ],
    "args": [
      {
        "name": "domain",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Which PocketBase. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The instance's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "pocketbase domain remove": {
    "usage": "pbc pocketbase domain remove <domain> --name <name> [--env <name>]",
    "summary": "Remove a custom domain.",
    "needs": [
      "target:pocketbases",
      {
        "explicit": true
      }
    ],
    "args": [
      {
        "name": "domain",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Which PocketBase. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The instance's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "pocketbase domain status": {
    "usage": "pbc pocketbase domain status [--name <name>] [--env <name>]",
    "summary": "Check whether the custom domain is reachable.",
    "needs": [
      "target:pocketbases"
    ],
    "args": [],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Which PocketBase. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The instance's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "frontend ls": {
    "usage": "pbc frontend ls",
    "summary": "List frontends in a project.",
    "args": [],
    "flags": []
  },
  "frontend info": {
    "usage": "pbc frontend info (<name>|--name <name>|--id <id>) [--env <name>]",
    "summary": "Show frontend details.",
    "needs": [
      "target:frontends"
    ],
    "args": [
      {
        "name": "name",
        "required": false,
        "description": "Positional name, alternative to --name/--id"
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Which frontend to show. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The site's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "frontend rm": {
    "usage": "pbc frontend rm (<name>|--name <name>|--id <id>) [--yes] [--env <name>]",
    "summary": "Delete a frontend.",
    "needs": [
      "target:frontends",
      {
        "explicit": true
      }
    ],
    "args": [
      {
        "name": "name",
        "required": false,
        "description": "Positional name, alternative to --name/--id"
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Which frontend to delete. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The site's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "frontend domain add": {
    "usage": "pbc frontend domain add <domain> --name <name> [--env <name>]",
    "summary": "Add a custom domain.",
    "needs": [
      "target:frontends",
      {
        "explicit": true
      }
    ],
    "args": [
      {
        "name": "domain",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Which frontend. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The site's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "frontend domain verify": {
    "usage": "pbc frontend domain verify <domain> --name <name> [--env <name>]",
    "summary": "Verify a custom domain.",
    "needs": [
      "target:frontends",
      {
        "explicit": true
      }
    ],
    "args": [
      {
        "name": "domain",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Which frontend. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The site's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "frontend domain remove": {
    "usage": "pbc frontend domain remove <domain> --name <name> [--env <name>]",
    "summary": "Remove a custom domain.",
    "needs": [
      "target:frontends",
      {
        "explicit": true
      }
    ],
    "args": [
      {
        "name": "domain",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Which frontend. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The site's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "frontend domain status": {
    "usage": "pbc frontend domain status [--name <name>] [--env <name>]",
    "summary": "Check whether the custom domain is reachable.",
    "needs": [
      "target:frontends"
    ],
    "args": [],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Which frontend. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The site's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "backend ls": {
    "usage": "pbc backend ls",
    "summary": "List backends in a project.",
    "args": [],
    "flags": []
  },
  "backend info": {
    "usage": "pbc backend info (<name>|--name <name>|--id <id>) [--env <name>]",
    "summary": "Show backend details.",
    "needs": [
      "target:backends"
    ],
    "args": [
      {
        "name": "name",
        "required": false,
        "description": "Positional name, alternative to --name/--id"
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Which backend to show. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The backend's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "backend rm": {
    "usage": "pbc backend rm (<name>|--name <name>|--id <id>) [--yes] [--env <name>]",
    "summary": "Delete a backend.",
    "needs": [
      "target:backends",
      {
        "explicit": true
      }
    ],
    "args": [
      {
        "name": "name",
        "required": false,
        "description": "Positional name, alternative to --name/--id"
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Which backend to delete. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The backend's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "backend domain add": {
    "usage": "pbc backend domain add <domain> --name <name> [--env <name>]",
    "summary": "Add a custom domain.",
    "needs": [
      "target:backends",
      {
        "explicit": true
      }
    ],
    "args": [
      {
        "name": "domain",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Which backend. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The backend's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "backend domain verify": {
    "usage": "pbc backend domain verify <domain> --name <name> [--env <name>]",
    "summary": "Verify a custom domain.",
    "needs": [
      "target:backends",
      {
        "explicit": true
      }
    ],
    "args": [
      {
        "name": "domain",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Which backend. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The backend's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "backend domain remove": {
    "usage": "pbc backend domain remove <domain> --name <name> [--env <name>]",
    "summary": "Remove a custom domain.",
    "needs": [
      "target:backends",
      {
        "explicit": true
      }
    ],
    "args": [
      {
        "name": "domain",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Which backend. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The backend's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "backend domain status": {
    "usage": "pbc backend domain status [--name <name>] [--env <name>]",
    "summary": "Check whether the custom domain is reachable.",
    "needs": [
      "target:backends"
    ],
    "args": [],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Which backend. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The backend's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "pocketbase create": {
    "usage": "pbc pocketbase create [<name>] [flags]",
    "summary": "Create a PocketBase instance.",
    "details": "Provisions a running instance with nothing deployed to it — no\npb_public, pb_hooks or pb_migrations — and waits until it answers. Use it to\nget a database before there is anything to deploy.\n\nThe instance is recorded in this directory's pbc.json under the target\nenvironment, exactly as a deploy would record it, so the next\n`pbc pocketbase deploy` here needs no --name. A directory bound to another\nkind, or an environment that already names an instance, is refused.\n\nIt gets a superuser account — your account email, and a generated password\nprinted once (readable afterwards with `pbc pocketbase info`). Override\neither with --admin-email/--admin-password. --backup restores a PocketBase\nbackup ZIP instead and preserves its existing superusers.\n\n`pbc pocketbase deploy` also creates an instance when there is none, so this\nis the explicit form for when there is nothing to package.",
    "args": [
      {
        "name": "name",
        "required": false,
        "description": "Positional name, alternative to --name"
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "What to call the instance. Asked for on a terminal when omitted."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to record the instance under. Defaults to the file's default, or production."
      },
      {
        "name": "location",
        "type": "string",
        "required": false,
        "description": "Region for the instance, on Starter. The platform picks when omitted."
      },
      {
        "name": "compute",
        "type": "string",
        "required": false,
        "description": "Compute to create on; asked for when there is a choice, or required under --no-input/--json."
      },
      {
        "name": "server",
        "type": "string",
        "required": false,
        "description": "Old name for --compute; scripts may keep using it.",
        "renamedTo": "compute"
      },
      {
        "name": "admin-email",
        "type": "string",
        "required": false,
        "description": "Superuser login; defaults to your account email."
      },
      {
        "name": "admin-password",
        "type": "string",
        "required": false,
        "description": "Superuser password, 12-20 characters. Generated and printed once when omitted."
      },
      {
        "name": "pb-version",
        "type": "string",
        "required": false,
        "description": "PocketBase release; defaults to pocketbaseVersion in pbc.json."
      },
      {
        "name": "dev",
        "type": "string",
        "required": false,
        "description": "Enable PocketBase dev mode: true or false."
      },
      {
        "name": "hooks-pool",
        "type": "string",
        "required": false,
        "description": "Hooks runtime pool size, 1-100."
      },
      {
        "name": "query-timeout",
        "type": "string",
        "required": false,
        "description": "Query timeout in seconds, 1-3600."
      },
      {
        "name": "backup",
        "type": "path",
        "required": false,
        "description": "PocketBase backup ZIP to restore during creation."
      }
    ]
  },
  "pocketbase deploy": {
    "usage": "pbc pocketbase deploy [--name <name>|--new <name>] [flags]",
    "summary": "Create or redeploy a PocketBase instance.",
    "details": "Packages pb_public, pb_hooks, and pb_migrations and ships them with the\ninstance, at the paths recorded in the \"build\" block of pbc.json. None of the\nthree is required: a directory that holds none still deploys, creating an\nempty instance and saying so.\n\nA redeploy ships them too: supported hook files (subdirectories included) go\nthrough the hooks route, which keeps the portal's editor in sync; pb_migrations\nis merged with the instance's; pb_public is replaced wholesale. New migrations\nare applied by the restart that follows.\n\nA new instance gets a superuser account — your account email and a generated\npassword printed once (readable afterwards with `pbc pocketbase info`).\nOverride either with --admin-email/--admin-password. Env vars are pushed only\nfrom the dotenv file this environment names; `pbc deploy --help` lists the\nmerge and --delete-missing/--skip-env/--force-env rules.",
    "needs": [
      "target:pocketbases",
      {
        "explicit": true
      }
    ],
    "args": [],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Which existing instance to redeploy; asked for when unbound."
      },
      {
        "name": "new",
        "type": "string",
        "required": false,
        "description": "Create a new PocketBase with this name. Fails if the name is taken."
      },
      {
        "name": "location",
        "type": "string",
        "required": false,
        "description": "Region for the deploy, on Starter. The platform picks when omitted."
      },
      {
        "name": "compute",
        "type": "string",
        "required": false,
        "description": "Compute to create on; asked for when there is a choice, or required under --no-input/--json."
      },
      {
        "name": "server",
        "type": "string",
        "required": false,
        "description": "Old name for --compute; scripts may keep using it.",
        "renamedTo": "compute"
      },
      {
        "name": "admin-email",
        "type": "string",
        "required": false,
        "description": "Superuser login; defaults to your account email."
      },
      {
        "name": "admin-password",
        "type": "string",
        "required": false,
        "description": "Superuser password, 12-20 characters. Generated and printed once when omitted."
      },
      {
        "name": "pb-version",
        "type": "string",
        "required": false,
        "description": "PocketBase release; defaults to pocketbaseVersion in pbc.json."
      },
      {
        "name": "skip-build",
        "type": "boolean",
        "required": false,
        "description": "Package without running the build command."
      },
      {
        "name": "skip-env",
        "type": "boolean",
        "required": false,
        "description": "Push no env vars this run."
      },
      {
        "name": "env-file",
        "type": "path",
        "required": false,
        "description": "Dotenv file to push; recorded in pbc.json for this environment."
      },
      {
        "name": "delete-missing",
        "type": "boolean",
        "required": false,
        "description": "Remove cloud vars the file does not list."
      },
      {
        "name": "force-env",
        "type": "boolean",
        "required": false,
        "description": "Push even when unchanged since the last push."
      },
      {
        "name": "zip",
        "type": "string",
        "required": false,
        "description": "Deploy this archive instead of building the directory."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment; defaults to the file's default or production."
      },
      {
        "name": "subdomain",
        "type": "string",
        "required": false,
        "description": "",
        "retired": {
          "since": "0.6.0",
          "note": "Frontends use uid addresses."
        }
      }
    ]
  },
  "pocketbase config get": {
    "usage": "pbc pocketbase config get [--name <instance>]",
    "summary": "Show PocketBase runtime configuration.",
    "needs": [
      "target:pocketbases",
      {
        "explicit": true
      }
    ],
    "args": [],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Which instance. Defaults to the directory binding."
      }
    ]
  },
  "pocketbase config set": {
    "usage": "pbc pocketbase config set [--name <instance>] [runtime flags]",
    "summary": "Update PocketBase runtime configuration.",
    "needs": [
      "target:pocketbases",
      {
        "explicit": true
      }
    ],
    "args": [],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Which instance. Defaults to the directory binding."
      },
      {
        "name": "dev",
        "type": "string",
        "required": false,
        "description": "true or false."
      },
      {
        "name": "hooks-pool",
        "type": "string",
        "required": false,
        "description": "Hooks pool size, 1-100."
      },
      {
        "name": "query-timeout",
        "type": "string",
        "required": false,
        "description": "Query timeout, 1-3600 seconds."
      }
    ]
  },
  "pocketbase superuser sync": {
    "usage": "pbc pocketbase superuser sync --email <email> --password <password> [--name <instance>]",
    "summary": "Add or update the managed PocketBase superuser.",
    "needs": [
      "target:pocketbases",
      {
        "explicit": true
      }
    ],
    "args": [],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Which instance. Defaults to the directory binding."
      },
      {
        "name": "email",
        "type": "string",
        "required": true,
        "description": "Managed superuser email."
      },
      {
        "name": "password",
        "type": "string",
        "required": true,
        "description": "Managed superuser password."
      }
    ]
  },
  "pocketbase hooks push": {
    "usage": "pbc pocketbase hooks push <dir> [--name <instance>]",
    "summary": "Upload every supported hook file in <dir> as a hook.",
    "details": "Hooks belong to one PocketBase instance. Name it with --name/--id, or let\nthe directory's pbc.json binding pick it.\n\nPocketBase runs only *.pb.js, but every supported text file beside them\n(.pb.js, .js, .mjs, .cjs, .json, .html, .htm, .css, .txt, .md, .csv, .xml, .svg, .yml, .yaml) is uploaded too, subdirectories\nincluded and keeping their relative path, so a required helper module or data\nfile resolves on the instance. At most 500 files per push.",
    "args": [
      {
        "name": "dir",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Which instance. Defaults to the directory's binding."
      }
    ]
  },
  "pocketbase hooks ls": {
    "usage": "pbc pocketbase hooks ls [--name <instance>]",
    "summary": "List uploaded hook files.",
    "details": "Lists hooks uploaded with `pbc pocketbase hooks push`. Hooks shipped\ninside a deploy archive run but are not recorded here, so this can read\nempty while hooks are live.",
    "args": [],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Which instance. Defaults to the directory's binding."
      }
    ]
  },
  "pocketbase hooks rm": {
    "usage": "pbc pocketbase hooks rm <filename> [--name <instance>]",
    "summary": "Delete a hook file.",
    "args": [
      {
        "name": "filename",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Which instance. Defaults to the directory's binding."
      }
    ]
  },
  "frontend deploy": {
    "usage": "pbc frontend deploy [--name <name>|--new <name>] [flags]",
    "summary": "Build, package, and deploy a static site.",
    "details": "Runs the build command, zips the output directory, and uploads it. Both\ncome from the \"build\" block in pbc.json, inferred from the directory\n(vite/svelte/angular/next config, package.json build script) and written\nthere on the first deploy.\n\nFrontends have no cloud env store — build-time variables are baked into the\nbundle, so there is no --env-file flag here.\n\nA site is served from an address the platform assigns and never changes:\n<id>.<compute>.pocketbasecloud.com. To put a domain of your own in front of\nit, use pbc frontend domain add.",
    "needs": [
      "target:frontends",
      {
        "explicit": true
      }
    ],
    "args": [],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Which existing frontend to redeploy; asked for when unbound."
      },
      {
        "name": "new",
        "type": "string",
        "required": false,
        "description": "Create a new frontend with this name. Fails if the name is taken."
      },
      {
        "name": "zip",
        "type": "string",
        "required": false,
        "description": "Deploy this archive instead of building the directory."
      },
      {
        "name": "skip-build",
        "type": "boolean",
        "required": false,
        "description": "Package without running the build command."
      },
      {
        "name": "location",
        "type": "string",
        "required": false,
        "description": "Region for the deploy. The platform picks when omitted."
      },
      {
        "name": "compute",
        "type": "string",
        "required": false,
        "description": "Compute to create on; asked for when there is a choice, or required under --no-input/--json."
      },
      {
        "name": "server",
        "type": "string",
        "required": false,
        "description": "Old name for --compute; scripts may keep using it.",
        "renamedTo": "compute"
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment; defaults to the file's default or production."
      },
      {
        "name": "subdomain",
        "type": "string",
        "required": false,
        "description": "",
        "retired": {
          "since": "0.6.0",
          "note": "Frontends use uid addresses."
        }
      }
    ]
  },
  "backend deploy": {
    "usage": "pbc backend deploy [--name <name>|--new <name>] [flags]",
    "summary": "Build, package, and deploy a backend.",
    "details": "Runs the build command and uploads the result. The runtime, build command,\nand output directory come from the \"build\" block in pbc.json, inferred from the\ndirectory (deno.json, bun.lockb, next.config.*, package.json) and written there\non the first deploy.\n\ndeno, bun, and nodejs ship their source — the platform installs dependencies\non start, so node_modules is excluded. Where there is a build command, deploy\ninstalls its dependencies first when they are missing, with the package\nmanager the lockfile names.\n\nnextjs ships a prebuilt bundle: deploy adds output: \"standalone\" to\nnext.config.* before building (and says so) unless the config already sets\noutput, then assembles .next/standalone, .next/static, and public, starting\nwith node server.js. output: \"export\" is a static site — deploy it with\npbc frontend deploy instead.",
    "needs": [
      "target:backends",
      {
        "explicit": true
      }
    ],
    "args": [],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Which existing backend to redeploy; asked for when unbound."
      },
      {
        "name": "new",
        "type": "string",
        "required": false,
        "description": "Create a new backend with this name. Fails if the name is taken."
      },
      {
        "name": "runtime",
        "type": "string",
        "required": false,
        "choices": [
          "deno",
          "bun",
          "nodejs",
          "nextjs"
        ],
        "description": "Defaults to build.runtime in pbc.json, else inferred."
      },
      {
        "name": "start",
        "type": "string",
        "required": false,
        "description": "Command to run; defaults to build.startCommand."
      },
      {
        "name": "compute",
        "type": "string",
        "required": false,
        "description": "Compute to create on; asked for when there is a choice, or required under --no-input/--json."
      },
      {
        "name": "server",
        "type": "string",
        "required": false,
        "description": "Old name for --compute; scripts may keep using it.",
        "renamedTo": "compute"
      },
      {
        "name": "zip",
        "type": "string",
        "required": false,
        "description": "Deploy this archive instead of building the directory."
      },
      {
        "name": "skip-build",
        "type": "boolean",
        "required": false,
        "description": "Package without running the build command."
      },
      {
        "name": "skip-env",
        "type": "boolean",
        "required": false,
        "description": "Push no env vars this run."
      },
      {
        "name": "env-file",
        "type": "path",
        "required": false,
        "description": "Dotenv file to push; recorded in pbc.json for this environment."
      },
      {
        "name": "delete-missing",
        "type": "boolean",
        "required": false,
        "description": "Remove cloud vars the file does not list."
      },
      {
        "name": "force-env",
        "type": "boolean",
        "required": false,
        "description": "Push even when unchanged since the last push."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment; defaults to the file's default or production."
      }
    ]
  },
  "deploy": {
    "usage": "pbc deploy [pocketbase|frontend|backend] [<name>] [flags]",
    "summary": "Deploy this directory, detecting what kind of resource it is.",
    "details": "Works out whether the directory holds a PocketBase instance, a static\nsite, or a backend, then runs that kind's deploy — `pbc pocketbase deploy`,\n`pbc frontend deploy`, or `pbc backend deploy`. Every flag those commands\naccept works here and is passed straight through.\n\nThe first of these that applies decides:\n\n  1. The \"kind\" recorded in pbc.json by a previous deploy — never re-guessed.\n  2. pb_hooks/, pb_migrations/, or pb_public/ — a PocketBase instance.\n  3. next.config.*: \"output\": \"export\" is a static site, anything else a backend.\n  4. vite / svelte / vue config, or angular.json — a frontend.\n  5. deno.json(c) — a backend.\n  6. package.json dependencies, then its scripts: a server dep or a \"start\"\n     script is a backend; a bundler dep or a lone \"build\" script a frontend.\n  7. index.html in the directory or public/, dist/, build/, or out/ — a frontend.\n\nThe detected kind and the file that decided it are printed before the deploy\nruns. A leading kind word overrides the detection outright:\n\n  pbc deploy backend            # deploy as a backend, whatever is here\n  pbc deploy frontend web       # …and redeploy the existing \"web\"\n\nEnv vars are pushed only from the dotenv file each environment names —\nnothing by default. The first deploy of an environment asks which file (or\nnone) and records it in pbc.json. Pushing merges, keeping cloud-only keys;\n--delete-missing makes the file the whole truth, and --skip-env pushes\nnothing this run. An unchanged file is not re-uploaded without --force-env.\n\nWhen nothing in the directory points either way you are asked on a terminal;\nunder --no-input or --json you get an error naming the three explicit\ncommands.",
    "args": [
      {
        "name": "kind",
        "required": false,
        "description": "pocketbase, frontend, or backend; detected from the directory when omitted"
      },
      {
        "name": "name",
        "required": false,
        "description": "The existing resource to redeploy, same as --name; create with --new"
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Which existing instance to redeploy; asked for when unbound."
      },
      {
        "name": "new",
        "type": "string",
        "required": false,
        "description": "Create a new PocketBase with this name. Fails if the name is taken."
      },
      {
        "name": "location",
        "type": "string",
        "required": false,
        "description": "Region for the deploy, on Starter. The platform picks when omitted."
      },
      {
        "name": "compute",
        "type": "string",
        "required": false,
        "description": "Compute to create on; asked for when there is a choice, or required under --no-input/--json."
      },
      {
        "name": "server",
        "type": "string",
        "required": false,
        "description": "Old name for --compute; scripts may keep using it.",
        "renamedTo": "compute"
      },
      {
        "name": "admin-email",
        "type": "string",
        "required": false,
        "description": "Superuser login; defaults to your account email."
      },
      {
        "name": "admin-password",
        "type": "string",
        "required": false,
        "description": "Superuser password, 12-20 characters. Generated and printed once when omitted."
      },
      {
        "name": "pb-version",
        "type": "string",
        "required": false,
        "description": "PocketBase release; defaults to pocketbaseVersion in pbc.json."
      },
      {
        "name": "skip-build",
        "type": "boolean",
        "required": false,
        "description": "Package without running the build command."
      },
      {
        "name": "skip-env",
        "type": "boolean",
        "required": false,
        "description": "Push no env vars this run."
      },
      {
        "name": "env-file",
        "type": "path",
        "required": false,
        "description": "Dotenv file to push; recorded in pbc.json for this environment."
      },
      {
        "name": "delete-missing",
        "type": "boolean",
        "required": false,
        "description": "Remove cloud vars the file does not list."
      },
      {
        "name": "force-env",
        "type": "boolean",
        "required": false,
        "description": "Push even when unchanged since the last push."
      },
      {
        "name": "zip",
        "type": "string",
        "required": false,
        "description": "Deploy this archive instead of building the directory."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment; defaults to the file's default or production."
      },
      {
        "name": "subdomain",
        "type": "string",
        "required": false,
        "description": "",
        "retired": {
          "since": "0.6.0",
          "note": "Frontends use uid addresses."
        }
      },
      {
        "name": "runtime",
        "type": "string",
        "required": false,
        "choices": [
          "deno",
          "bun",
          "nodejs",
          "nextjs"
        ],
        "description": "Defaults to build.runtime in pbc.json, else inferred."
      },
      {
        "name": "start",
        "type": "string",
        "required": false,
        "description": "Command to run; defaults to build.startCommand."
      }
    ]
  },
  "project ls": {
    "usage": "pbc project ls",
    "summary": "List projects.",
    "args": [],
    "flags": []
  },
  "project create": {
    "usage": "pbc project create <name>",
    "summary": "Create a project.",
    "args": [
      {
        "name": "name",
        "required": true
      }
    ],
    "flags": []
  },
  "project use": {
    "usage": "pbc project use <name|id>",
    "summary": "Set the current project.",
    "args": [
      {
        "name": "name|id",
        "required": true
      }
    ],
    "flags": []
  },
  "project rm": {
    "usage": "pbc project rm <name|id> [--yes]",
    "summary": "Delete a project.",
    "args": [
      {
        "name": "name|id",
        "required": true
      }
    ],
    "flags": []
  },
  "compute ls": {
    "usage": "pbc compute ls",
    "summary": "List the compute your account can deploy to.",
    "details": "Compute is provisioned by the platform, not the CLI. This lists your\naccount's own dedicated compute — the ids `--compute <id>` accepts on a\ndeploy. The shared pool is not listed: on every plan except Pro the\nplatform picks from it by capacity and the flag is unnecessary.",
    "args": [],
    "flags": []
  },
  "server ls": {
    "usage": "pbc server ls",
    "summary": "List the compute your account can deploy to (alias of compute ls).",
    "args": [],
    "flags": []
  },
  "locations": {
    "usage": "pbc locations",
    "summary": "List the regions a deploy can actually land in.",
    "details": "The regions of the shared platform pool for the plan a deploy is placed\nagainst — what `--location <loc>` accepts on `pocketbase create` and\n`frontend deploy`. Not the provider catalog: most regions a\nprovider sells hold no server of ours, and a deploy aimed at one fails\nwith `noServerAvailable`.\n\nWith `--project`, the answer is for that project's owner (org-aware);\nwithout it, for the caller.",
    "args": [],
    "flags": []
  },
  "env ls": {
    "usage": "pbc env ls --target pocketbase|backend --name <n> [--env <name>]",
    "summary": "List environment variables.",
    "details": "Names only. The platform stores values encrypted and its list endpoint\nnever returns plaintext, so there is nothing for the CLI to show —\nread a value from the app itself, or overwrite it with `env set`.\nWithout --name/--id, a terminal offers a picker.",
    "args": [],
    "flags": [
      {
        "name": "target",
        "type": "string",
        "required": true,
        "choices": [
          "pocketbase",
          "backend"
        ],
        "description": "pocketbase or backend — which kind's variables."
      },
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Which resource's variables. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The resource's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "env set": {
    "usage": "pbc env set KEY=VALUE --target pocketbase|backend --name <n> [--env <name>]",
    "summary": "Set an environment variable.",
    "args": [
      {
        "name": "KEY=VALUE",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "target",
        "type": "string",
        "required": true,
        "choices": [
          "pocketbase",
          "backend"
        ],
        "description": "pocketbase or backend — which kind's variables."
      },
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Which resource's variables. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The resource's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "env rm": {
    "usage": "pbc env rm KEY --target pocketbase|backend --name <n> [--env <name>]",
    "summary": "Remove an environment variable.",
    "args": [
      {
        "name": "KEY",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "target",
        "type": "string",
        "required": true,
        "choices": [
          "pocketbase",
          "backend"
        ],
        "description": "pocketbase or backend — which kind's variables."
      },
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Which resource's variables. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The resource's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "env import": {
    "usage": "pbc env import <.env> --target pocketbase|backend --name <n> [--delete-missing] [--env <name>]",
    "summary": "Bulk-import variables from a .env file.",
    "details": "Merges: keys in the file are written, cloud-only keys are left alone.\n--delete-missing makes the file the whole truth — cloud variables it does not\nlist are removed too, after a confirmation that --no-input does not waive\n(without a way to ask, the import stops and names --yes).",
    "args": [
      {
        "name": ".env",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "target",
        "type": "string",
        "required": true,
        "choices": [
          "pocketbase",
          "backend"
        ],
        "description": "pocketbase or backend — which kind's variables."
      },
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Which resource's variables. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The resource's id, alternative to --name."
      },
      {
        "name": "delete-missing",
        "type": "boolean",
        "required": false,
        "description": "Remove cloud variables the file does not list."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      }
    ]
  },
  "environments": {
    "usage": "pbc environments",
    "summary": "List the environments recorded in ./pbc.json.",
    "details": "Shows which cloud resource each environment of this directory deploys\nto, and which one a bare deploy targets. Reads the file only — no\nlogin, no network call.\n\nEnvironments are created by deploying or linking with --env:\n  pbc frontend deploy --env staging --name web-staging",
    "args": [],
    "flags": []
  },
  "logs": {
    "usage": "pbc logs <pocketbase|backend> --name <n> [-f] [--lines <n>] [--env <name>]",
    "summary": "Stream logs for a PocketBase instance or backend.",
    "details": "Prints the last --lines entries (50 by default, 1000 max) and stops; with\n--follow it keeps printing until interrupted.",
    "args": [
      {
        "name": "pocketbase|backend",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Which instance's logs. Asked for when omitted."
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "description": "The instance's id, alternative to --name."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to target."
      },
      {
        "name": "follow",
        "type": "boolean",
        "required": false,
        "description": "Keep printing as new log lines arrive."
      },
      {
        "name": "lines",
        "type": "string",
        "required": false,
        "description": "How much history to print first. 1-1000, default 50."
      }
    ]
  },
  "init": {
    "usage": "pbc init [pocketbase|frontend|backend] [--force] [--env <name>]",
    "summary": "Write this directory's build config into pbc.json.",
    "details": "Inspects the directory and records how it should be built and packaged: the\nbuild command, output directory, backend runtime, or a PocketBase project's\npb_public / pb_hooks / pb_migrations paths. Nothing in the cloud is touched,\nand no login is needed.\n\nDeploy infers the same block when pbc.json has none, so this command is\noptional — it lets you see and edit the guess before anything ships. An\nexisting block is left alone unless --force is passed.\n\nOn a terminal it also asks which environment this directory deploys to and\nrecords it as the default.",
    "args": [
      {
        "name": "kind",
        "required": false,
        "description": "pocketbase, frontend, or backend; defaults to the bound resource"
      }
    ],
    "flags": [
      {
        "name": "force",
        "type": "boolean",
        "required": false,
        "description": "Overwrite an existing build block."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "Which pbc.json environment to make the default."
      }
    ]
  },
  "ci init": {
    "usage": "pbc ci init [pb|frontend|backend] [flags]",
    "summary": "Write a GitHub Actions workflow that deploys this directory.",
    "details": "Writes .github/workflows/deploy.yml (or deploy-<path>.yml for a nested\ndirectory) using the official pocketbasecloud/cli/action. Nothing in the cloud\nis touched, and no login is needed — like `pbc init`, it only inspects the\ndirectory and the surrounding git repo.\n\nThe kind comes from the argument or pbc.json's binding; the branch from the\none checked out. An existing file is left alone unless --force is passed.\n\nIt then prints the remaining one-time step: a CLI access token from the\nportal's Account page, saved as the repository secret PBC_TOKEN.",
    "args": [
      {
        "name": "kind",
        "required": false,
        "description": "pb, frontend, or backend; defaults to the bound resource"
      }
    ],
    "flags": [
      {
        "name": "out",
        "type": "string",
        "required": false,
        "description": "Workflow file path. Defaults under .github/workflows/."
      },
      {
        "name": "branch",
        "type": "string",
        "required": false,
        "description": "Branch to deploy on push. Defaults to the branch currently checked out."
      },
      {
        "name": "force",
        "type": "boolean",
        "required": false,
        "description": "Overwrite an existing workflow file."
      },
      {
        "name": "env",
        "type": "string",
        "required": false,
        "description": "pbc.json environment to pin in the workflow. Only --env is written; PBC_ENV is ignored, because the answer is committed."
      }
    ]
  },
  "plan": {
    "usage": "pbc plan",
    "summary": "Show the current plan and the upgrade link.",
    "details": "Upgrades your account's plan. To update the pbc binary itself, see `pbc self upgrade`.",
    "args": [],
    "flags": []
  },
  "admin use": {
    "usage": "pbc admin use [<url>] [--name <profile>]",
    "summary": "Select a PocketBase instance, creating or updating its profile from a URL.",
    "args": [
      {
        "name": "url",
        "required": false
      }
    ],
    "flags": [
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Profile name (defaults to the URL)"
      }
    ]
  },
  "admin login": {
    "usage": "pbc admin login [--url <url>] [flags]",
    "summary": "Log in as the instance superuser. --url creates the profile in one step.",
    "args": [],
    "flags": [
      {
        "name": "url",
        "type": "string",
        "required": false,
        "description": "Instance URL; its profile is created when it is new"
      },
      {
        "name": "name",
        "type": "string",
        "required": false,
        "description": "Profile name for --url (defaults to the URL)"
      },
      {
        "name": "email",
        "type": "string",
        "required": false,
        "description": "Superuser email (prompts when omitted)"
      },
      {
        "name": "password",
        "type": "string",
        "required": false,
        "description": "Superuser password (prompts when omitted)"
      }
    ]
  },
  "admin logout": {
    "usage": "pbc admin logout [--remove]",
    "summary": "Log out of the current instance profile. --remove also forgets it.",
    "args": [],
    "flags": [
      {
        "name": "remove",
        "type": "boolean",
        "required": false,
        "description": "Also forget the profile"
      }
    ]
  },
  "admin whoami": {
    "usage": "pbc admin whoami",
    "summary": "Show the active instance profile.",
    "args": [],
    "flags": []
  },
  "admin profiles": {
    "usage": "pbc admin profiles",
    "summary": "List saved instance logins and which one is active.",
    "args": [],
    "flags": []
  },
  "local init": {
    "usage": "pbc local init [<version>] [--dir <d>] [--force]",
    "summary": "Download a PocketBase binary and scaffold a local project.",
    "details": "Downloads the binary for this OS and CPU, then creates pb_hooks/,\npb_migrations/, a README.md, .gitignore entries (which exclude the\nbinary and pb_data/), and a pocketbaseVersion pin in pbc.json. Existing\nfiles are never overwritten. Omit <version> for the latest release;\n--force re-downloads the binary only.\n\nStart the instance afterwards with `./pocketbase serve`.",
    "args": [
      {
        "name": "version",
        "required": false,
        "description": "Release to install, e.g. 0.39.9. Defaults to latest."
      }
    ],
    "flags": [
      {
        "name": "dir",
        "type": "string",
        "required": false,
        "description": "Directory to install into. Defaults to the current directory."
      },
      {
        "name": "force",
        "type": "boolean",
        "required": false,
        "description": "Re-download the binary even if it is already present."
      },
      {
        "name": "os",
        "type": "string",
        "required": false,
        "choices": [
          "darwin",
          "linux",
          "windows"
        ],
        "description": "Override OS detection: darwin, linux, or windows."
      },
      {
        "name": "arch",
        "type": "string",
        "required": false,
        "choices": [
          "amd64",
          "arm64",
          "armv7",
          "ppc64le",
          "s390x"
        ],
        "description": "Override CPU detection: amd64, arm64, armv7, ppc64le, or s390x."
      }
    ]
  },
  "local install": {
    "usage": "pbc local install [<version>] [flags]",
    "summary": "Download a PocketBase binary and record the version pin.",
    "details": "Like `pbc local init` without the scaffolding. --os/--arch override platform\ndetection to fetch a build for another machine.\n\nStart the instance afterwards with `./pocketbase serve`.",
    "args": [
      {
        "name": "version",
        "required": false,
        "description": "Release to install, e.g. 0.39.9. Defaults to latest."
      }
    ],
    "flags": [
      {
        "name": "dir",
        "type": "string",
        "required": false,
        "description": "Directory to install into. Defaults to the current directory."
      },
      {
        "name": "force",
        "type": "boolean",
        "required": false,
        "description": "Re-download the binary even if it is already present."
      },
      {
        "name": "os",
        "type": "string",
        "required": false,
        "choices": [
          "darwin",
          "linux",
          "windows"
        ],
        "description": "Override OS detection: darwin, linux, or windows."
      },
      {
        "name": "arch",
        "type": "string",
        "required": false,
        "choices": [
          "amd64",
          "arm64",
          "armv7",
          "ppc64le",
          "s390x"
        ],
        "description": "Override CPU detection: amd64, arm64, armv7, ppc64le, or s390x."
      }
    ]
  },
  "local versions": {
    "usage": "pbc local versions [--all] [--pre]",
    "summary": "List available PocketBase versions.",
    "details": "Reads the live GitHub releases. Shows the 20 newest by semver; --all\nlists every release and --pre includes prereleases. Falls back to a\nbuilt-in list, clearly labelled, when GitHub is unreachable.",
    "args": [],
    "flags": [
      {
        "name": "all",
        "type": "boolean",
        "required": false,
        "description": "List every release, not just the 20 newest."
      },
      {
        "name": "pre",
        "type": "boolean",
        "required": false,
        "description": "Include prereleases."
      }
    ]
  },
  "local which": {
    "usage": "pbc local which [--dir <d>]",
    "summary": "Show the installed PocketBase binary and its pinned version.",
    "args": [],
    "flags": [
      {
        "name": "dir",
        "type": "string",
        "required": false,
        "description": "Directory to look in. Defaults to the current directory."
      },
      {
        "name": "os",
        "type": "string",
        "required": false,
        "choices": [
          "darwin",
          "linux",
          "windows"
        ],
        "description": "Override OS detection: darwin, linux, or windows."
      },
      {
        "name": "arch",
        "type": "string",
        "required": false,
        "choices": [
          "amd64",
          "arm64",
          "armv7",
          "ppc64le",
          "s390x"
        ],
        "description": "Override CPU detection: amd64, arm64, armv7, ppc64le, or s390x."
      }
    ]
  },
  "self upgrade": {
    "usage": "pbc self upgrade [<version>] [--check] [--force]",
    "summary": "Update pbc itself to the latest release.",
    "details": "Downloads the release archive for this OS and CPU, verifies its\nSHA-256 against the release's checksums.txt, and replaces the running\nbinary. Nothing is changed unless the checksum matches.\n\nPass a <version> to install a specific release, including an older one\nto roll back. --check reports what is available without installing;\n--force reinstalls the version you already have.\n\nOnly a standalone binary (the installer, or a release archive) can be\nreplaced in place; a from-source install is updated by updating its clone.\n\npbc also mentions a newer release on stderr at most once a day;\nPBC_NO_UPDATE_CHECK=1 disables that. To change your plan, see `pbc plan`.",
    "args": [
      {
        "name": "version",
        "required": false,
        "description": "Release to install, e.g. 0.2.4. Defaults to the latest."
      }
    ],
    "flags": [
      {
        "name": "check",
        "type": "boolean",
        "required": false,
        "description": "Report the available version without installing it"
      },
      {
        "name": "force",
        "type": "boolean",
        "required": false,
        "description": "Reinstall even when already on the target version"
      }
    ]
  },
  "admin collections ls": {
    "usage": "pbc admin collections ls",
    "summary": "List collections.",
    "args": [],
    "flags": []
  },
  "admin collections get": {
    "usage": "pbc admin collections get <idOrName>",
    "summary": "Show a collection.",
    "args": [
      {
        "name": "idOrName",
        "required": true
      }
    ],
    "flags": []
  },
  "admin collections create": {
    "usage": "pbc admin collections create <name> [--type base|auth|view]",
    "summary": "Create a collection.",
    "args": [
      {
        "name": "name",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "type",
        "type": "string",
        "required": false,
        "choices": [
          "base",
          "auth",
          "view"
        ],
        "description": "Collection type. One of base, auth, view."
      },
      {
        "name": "data",
        "type": "string",
        "required": false,
        "description": "Full JSON definition — creates a collection with fields in one step."
      }
    ]
  },
  "admin collections update": {
    "usage": "pbc admin collections update <idOrName> '<json>'",
    "summary": "Update a collection.",
    "args": [
      {
        "name": "idOrName",
        "required": true
      },
      {
        "name": "json",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "data",
        "type": "string",
        "required": false,
        "description": "The JSON definition, alternative to the positional."
      }
    ]
  },
  "admin collections rm": {
    "usage": "pbc admin collections rm <idOrName> [--yes]",
    "summary": "Delete a collection.",
    "args": [
      {
        "name": "idOrName",
        "required": true
      }
    ],
    "flags": []
  },
  "admin collections export": {
    "usage": "pbc admin collections export [--out <file>]",
    "summary": "Export all collections to JSON.",
    "args": [],
    "flags": [
      {
        "name": "out",
        "type": "string",
        "required": false,
        "description": "Where to write the file. Defaults to collections.json."
      }
    ]
  },
  "admin collections import": {
    "usage": "pbc admin collections import <file.json> [--delete-missing]",
    "summary": "Import collections from JSON. --delete-missing drops collections not in the file.",
    "args": [
      {
        "name": "file.json",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "delete-missing",
        "type": "boolean",
        "required": false,
        "description": "Drop collections not in the file."
      }
    ]
  },
  "admin records ls": {
    "usage": "pbc admin records ls <collection> [--filter <expr>] [--sort <expr>] [--page <n>] [--per-page <n>]",
    "summary": "List records in a collection.",
    "args": [
      {
        "name": "collection",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "filter",
        "type": "string",
        "required": false,
        "description": "PocketBase filter expression."
      },
      {
        "name": "sort",
        "type": "string",
        "required": false,
        "description": "Sort expression, e.g. -created."
      },
      {
        "name": "page",
        "type": "string",
        "required": false,
        "description": "Page number."
      },
      {
        "name": "per-page",
        "type": "string",
        "required": false,
        "description": "Records per page."
      }
    ]
  },
  "admin records get": {
    "usage": "pbc admin records get <collection> <id>",
    "summary": "Show a record.",
    "args": [
      {
        "name": "collection",
        "required": true
      },
      {
        "name": "id",
        "required": true
      }
    ],
    "flags": []
  },
  "admin records create": {
    "usage": "pbc admin records create <collection> '<json>'",
    "summary": "Create a record.",
    "args": [
      {
        "name": "collection",
        "required": true
      },
      {
        "name": "json",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "data",
        "type": "string",
        "required": false,
        "description": "The JSON payload, alternative to the positional."
      }
    ]
  },
  "admin records update": {
    "usage": "pbc admin records update <collection> <id> '<json>'",
    "summary": "Update a record.",
    "args": [
      {
        "name": "collection",
        "required": true
      },
      {
        "name": "id",
        "required": true
      },
      {
        "name": "json",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "data",
        "type": "string",
        "required": false,
        "description": "The JSON payload, alternative to the positional."
      }
    ]
  },
  "admin records rm": {
    "usage": "pbc admin records rm <collection> <id> [--yes]",
    "summary": "Delete a record.",
    "args": [
      {
        "name": "collection",
        "required": true
      },
      {
        "name": "id",
        "required": true
      }
    ],
    "flags": []
  },
  "admin rules get": {
    "usage": "pbc admin rules get <collection>",
    "summary": "Show API rules.",
    "args": [
      {
        "name": "collection",
        "required": true
      }
    ],
    "flags": []
  },
  "admin rules set": {
    "usage": "pbc admin rules set <collection> [--list-rule <expr>] [--view-rule <expr>] [--create-rule <expr>] [--update-rule <expr>] [--delete-rule <expr>]",
    "summary": "Update API rules. Pass 'null' as a value to clear a rule.",
    "args": [
      {
        "name": "collection",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "list-rule",
        "type": "string",
        "required": false,
        "description": "The list rule expression. 'null' clears it."
      },
      {
        "name": "view-rule",
        "type": "string",
        "required": false,
        "description": "The view rule expression. 'null' clears it."
      },
      {
        "name": "create-rule",
        "type": "string",
        "required": false,
        "description": "The create rule expression. 'null' clears it."
      },
      {
        "name": "update-rule",
        "type": "string",
        "required": false,
        "description": "The update rule expression. 'null' clears it."
      },
      {
        "name": "delete-rule",
        "type": "string",
        "required": false,
        "description": "The delete rule expression. 'null' clears it."
      }
    ]
  },
  "admin auth": {
    "usage": "pbc admin auth <collection> config [--set '<field>=<json>']",
    "summary": "View or edit an auth collection's auth-related settings.",
    "details": "Without --set, prints the current value of: authRule, manageRule, authAlert,\noauth2, passwordAuth, mfa, otp, verificationTemplate, resetPasswordTemplate.\n\n--set '<field>=<json>' replaces that field entirely, so run without --set\nfirst when the field already has content you need to keep (e.g.\noauth2.providers) and include it in the json. Collection and field names as\nin the admin UI.\n\n  pbc admin auth users config\n  pbc admin auth users config --set 'passwordAuth={\"enabled\":true,\"identityFields\":[\"email\"]}'",
    "args": [
      {
        "name": "collection",
        "required": true
      },
      {
        "name": "config",
        "required": true,
        "description": "Literal subcommand keyword"
      }
    ],
    "flags": [
      {
        "name": "set",
        "type": "string",
        "required": false,
        "description": "Replace one field entirely, as '<field>=<json>'."
      }
    ]
  },
  "admin settings get": {
    "usage": "pbc admin settings get",
    "summary": "Show all instance settings.",
    "args": [],
    "flags": []
  },
  "admin settings mail": {
    "usage": "pbc admin settings mail",
    "summary": "Show SMTP settings.",
    "args": [],
    "flags": []
  },
  "admin settings mail set": {
    "usage": "pbc admin settings mail set '<json>'",
    "summary": "Update SMTP settings.",
    "args": [
      {
        "name": "json",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "data",
        "type": "string",
        "required": false,
        "description": "The JSON settings, alternative to the positional."
      }
    ]
  },
  "admin settings mail test": {
    "usage": "pbc admin settings mail test <email>",
    "summary": "Send a test email.",
    "args": [
      {
        "name": "email",
        "required": true
      }
    ],
    "flags": []
  },
  "admin settings s3": {
    "usage": "pbc admin settings s3",
    "summary": "Show S3 storage settings.",
    "args": [],
    "flags": []
  },
  "admin settings s3 set": {
    "usage": "pbc admin settings s3 set '<json>'",
    "summary": "Update S3 storage settings.",
    "args": [
      {
        "name": "json",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "data",
        "type": "string",
        "required": false,
        "description": "The JSON settings, alternative to the positional."
      }
    ]
  },
  "admin settings s3 test": {
    "usage": "pbc admin settings s3 test",
    "summary": "Test the S3 connection.",
    "args": [],
    "flags": []
  },
  "admin settings backup ls": {
    "usage": "pbc admin settings backup ls",
    "summary": "List backups.",
    "args": [],
    "flags": []
  },
  "admin settings backup create": {
    "usage": "pbc admin settings backup create [<name>]",
    "summary": "Create a backup.",
    "args": [
      {
        "name": "name",
        "required": false
      }
    ],
    "flags": []
  },
  "admin settings backup rm": {
    "usage": "pbc admin settings backup rm <key> [--yes]",
    "summary": "Delete a backup.",
    "args": [
      {
        "name": "key",
        "required": true
      }
    ],
    "flags": []
  },
  "admin settings backup download": {
    "usage": "pbc admin settings backup download <key> [--out <file>]",
    "summary": "Download a backup.",
    "args": [
      {
        "name": "key",
        "required": true
      }
    ],
    "flags": [
      {
        "name": "out",
        "type": "string",
        "required": false,
        "description": "Where to write the file. Defaults to the backup key."
      }
    ]
  },
  "admin cron ls": {
    "usage": "pbc admin cron ls",
    "summary": "List cron jobs.",
    "args": [],
    "flags": []
  },
  "admin cron run": {
    "usage": "pbc admin cron run <jobId>",
    "summary": "Run a cron job now.",
    "args": [
      {
        "name": "jobId",
        "required": true
      }
    ],
    "flags": []
  },
  "admin requests": {
    "usage": "pbc admin requests [flags]",
    "summary": "Show instance request logs. -f follows new entries.",
    "args": [],
    "flags": [
      {
        "name": "filter",
        "type": "string",
        "required": false,
        "description": "PocketBase filter expression."
      },
      {
        "name": "page",
        "type": "string",
        "required": false,
        "description": "Page number."
      },
      {
        "name": "per-page",
        "type": "string",
        "required": false,
        "description": "Log entries per page."
      },
      {
        "name": "follow",
        "type": "boolean",
        "required": false,
        "description": "Keep printing new log entries."
      }
    ]
  }
};
